version: '3.9'
services:
  glances:
    image: nicolargo/glances:latest-full
    restart: always
    ports:
      - "61208-61209:61208-61209"
    command: "glances -w"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./glances.conf:/glances/conf/glances.conf"
    pid: "host"